apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpleserver
  name: simpleserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: simpleserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleserver
    spec:
      containers:
      - image: fra.ocir.io/sefinland/mrinne/simpleserver:1.0
        imagePullPolicy: Always
        name: headertest
        ports:
        - containerPort: 3000
          name: default
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ocirsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30